# Build for combine file environment with yaml template to one file
# Last modify 2024/06/18
# Version 1.5

version: '3.3'

services:
  traefik:
    image: ${traefik_image}
    command:
    - --log.level=DEBUG
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=true
    - --entrypoints.web.address=:${port_web}
    ports:
    - ${port_web}:${port_web}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
    - traefik.enable=true
    - traefik.http.services.traefik.loadbalancer.server.port=8080
    - traefik.http.routers.traefik.rule=Host(`traefik.${domain}`)

  nginx:
    image: ${nginx_image}
    labels:
    - traefik.enable=true
    - traefik.http.services.nginx.loadbalancer.server.port=80
    - traefik.http.routers.nginx.rule=PathPrefix(`/`)

  whoami:
    image: ${whoami_image}
    labels:
    - traefik.enable=true
    - traefik.http.services.whoami.loadbalancer.server.port=80
    - traefik.http.routers.whoami.rule=Host(`whoami.${domain}`)
