# Build for create enviorment
# Last modify 2024/06/15
# Version 1.2

version: '3.3'

services:
  traefik:
    image: docker.io/library/traefik:v3.0.2
    command:
    - --log.level=DEBUG
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=true
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - "--accesslog=true"
    - "--accesslog.filepath=/log/access.log"
    - "--accesslog.format=json"
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.rule=Host(`traefik.sinaharaeeni.ir`)

  nginx:
    image: docker.io/library/nginx:1.27.0
    labels:
      - traefik.enable=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.routers.nginx.rule=PathPrefix(`/`)

  whoami:
    image: docker.io/traefik/whoami:v1.10.2
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.sinaharaeeni.ir`)
      - traefik.http.services.whoami.loadbalancer.server.port=80
